### ISSUE TITLE
app fizz when we enter value like this 

### ISSUE THREAD

**Issue by mitulmarsonia** [Hypercubesoft/HCLineChartView#1]
when we enter value like this 

    _hcLineChartView.xElements = [[NSMutableArray alloc] initWithObjects:@(120),@(120), nil];
    _hcLineChartView.yElements = [[NSMutableArray alloc] initWithObjects:@(119),@(119), nil];

Thank in advance.

**Comment by Hypercubesoft** [comment]
Hi,
We fixed the problem and updated code. You can test it out and let us know if that fixed your problem.

**Comment by mitulmarsonia** [comment]
Thank for update,

when we enter like this then fizz 

    _hcLineChartView.xElements = [[NSMutableArray alloc] initWithObjects:@(0),@(1), nil];
    _hcLineChartView.yElements = [[NSMutableArray alloc] initWithObjects:@(0),@(0), nil];

**Comment by Hypercubesoft** [comment]
We are going to test it with that data and if we find it not working we will update it again.

**Comment by Hypercubesoft** [comment]
Hi,
We fixed the problem with 0 values. You can try version 1.0.2

**Comment by lazar89nis** [comment]
Fixed
